#!/bin/bash
#
# builds and runs the containerized development environment
#
docker build --tag jenkinsfarm-dev .
docker run -it --rm --name jenkinsfarm-dev \
       --volume /var/run/docker.sock:/var/run/docker.sock \
       --volume $(which docker):/usr/bin/docker \
       --volume `pwd`:/host --workdir /host jenkinsfarm-dev
